import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        // Material Design 3 color tokens (from Stitch design)
        "background":                  "#15121b",
        "surface":                     "#15121b",
        "surface-dim":                 "#15121b",
        "surface-container-lowest":    "#0f0d15",
        "surface-container-low":       "#1d1a23",
        "surface-container":           "#211e27",
        "surface-container-high":      "#2c2832",
        "surface-container-highest":   "#37333d",
        "surface-bright":              "#3b3742",
        "surface-variant":             "#37333d",
        "on-surface":                  "#e7e0ed",
        "on-surface-variant":          "#cbc3d7",
        "on-background":               "#e7e0ed",
        "primary":                     "#d0bcff",
        "on-primary":                  "#3c0091",
        "primary-container":           "#a078ff",
        "primary-fixed":               "#e9ddff",
        "primary-fixed-dim":           "#d0bcff",
        "on-primary-container":        "#340080",
        "on-primary-fixed":            "#23005c",
        "on-primary-fixed-variant":    "#5516be",
        "inverse-primary":             "#6d3bd7",
        "surface-tint":                "#d0bcff",
        "secondary":                   "#4cd7f6",
        "on-secondary":                "#003640",
        "secondary-container":         "#03b5d3",
        "secondary-fixed":             "#acedff",
        "secondary-fixed-dim":         "#4cd7f6",
        "on-secondary-container":      "#00424e",
        "on-secondary-fixed":          "#001f26",
        "on-secondary-fixed-variant":  "#004e5c",
        "tertiary":                    "#c4c1fb",
        "on-tertiary":                 "#2d2a5b",
        "tertiary-container":          "#8e8bc2",
        "tertiary-fixed":              "#e3dfff",
        "tertiary-fixed-dim":          "#c4c1fb",
        "on-tertiary-container":       "#262354",
        "on-tertiary-fixed":           "#181445",
        "on-tertiary-fixed-variant":   "#444173",
        "outline":                     "#958ea0",
        "outline-variant":             "#494454",
        "error":                       "#ffb4ab",
        "on-error":                    "#690005",
        "error-container":             "#93000a",
        "on-error-container":          "#ffdad6",
        "inverse-surface":             "#e7e0ed",
        "inverse-on-surface":          "#322f39",
        // Legacy sky-* aliases → map to MD3 equivalents
        "sky-bg":      "#15121b",
        "sky-panel":   "#1d1a23",
        "sky-surface": "#211e27",
        "sky-border":  "#494454",
        "sky-accent":  "#d0bcff",
        "sky-cyan":    "#4cd7f6",
        "sky-text":    "#e7e0ed",
        "sky-muted":   "#958ea0",
      },
      fontFamily: {
        "display-lg":  ["Sora", "sans-serif"],
        "headline-lg": ["Sora", "sans-serif"],
        "headline-md": ["Sora", "sans-serif"],
        "body-lg":     ["Inter", "sans-serif"],
        "body-md":     ["Inter", "sans-serif"],
        "label-caps":  ["JetBrains Mono", "monospace"],
        "data-mono":   ["JetBrains Mono", "monospace"],
        "sora":        ["Sora", "sans-serif"],
        "inter":       ["Inter", "sans-serif"],
        "mono":        ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        "display-lg":  ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-lg":     ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md":     ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-caps":  ["12px", { lineHeight: "16px", letterSpacing: "0.1em", fontWeight: "500" }],
        "data-mono":   ["14px", { lineHeight: "20px", fontWeight: "400" }],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg:      "0.5rem",
        xl:      "0.75rem",
        "2xl":   "1rem",
        full:    "9999px",
      },
      spacing: {
        "sidebar-width":    "280px",
        "gutter":           "1.5rem",
        "panel-gap":        "1rem",
        "container-margin": "2rem",
        "touch-target":     "44px",
      },
      animation: {
        "fade-in":     "fade-in 0.8s cubic-bezier(0.16, 1, 0.3, 1) forwards",
        "fade-in-up":  "fadeInUp 0.8s ease-out forwards",
        "draw-line":   "drawLine 2s ease-in-out infinite alternate",
        "pulse-node":  "pulseNode 1.5s ease-in-out infinite alternate",
      },
      keyframes: {
        fadeInUp: {
          "0%":   { opacity: "0", transform: "translateY(20px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        drawLine: {
          "0%":   { width: "0%", opacity: "0" },
          "50%":  { opacity: "1" },
          "100%": { width: "100%", opacity: "0.5" },
        },
        pulseNode: {
          "0%":   { transform: "scale(0.8)", opacity: "0.5", boxShadow: "0 0 0 0 rgba(76, 215, 246, 0.4)" },
          "100%": { transform: "scale(1.2)", opacity: "1",   boxShadow: "0 0 10px 5px rgba(76, 215, 246, 0)" },
        },
      },
    },
  },
  plugins: [],
};

export default config;
